services:
  - type: web
    name: carbs_api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.api.main:app --host 0.0.0.0 --port 10000
    envVars: []
    plan: free
    pythonVersion: 3.12.8
